// src/lib/components/delete-modal.svelte
<script>
  import * as Dialog from "$lib/components/ui/dialog";
  import { Button } from "$lib/components/ui/button";

  export let open = false;
  export let onClose = () => {};
  export let onConfirm = () => {};
  export let objectId = null;
</script>

<Dialog.Root {open} onOpenChange={onClose}>
  <Dialog.Content class="sm:max-w-[425px]">
    <Dialog.Header>
      <Dialog.Title>Confirm deletion</Dialog.Title>
      <Dialog.Description>This cannot be undone!</Dialog.Description>
    </Dialog.Header>
    <Dialog.Footer>
      <Button variant="outline" on:click={onClose}>Cancel</Button>
      <Button
        variant="destructive"
        on:click={() => {
          onConfirm(objectId);
          onClose();
        }}
      >
        Delete
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

// src/components/DeleteModal.jsx
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { DialogClose } from "@radix-ui/react-dialog"

export function DeleteModal({ modalOpen, onClose, onConfirm, objectId }) {
    return (
        <Dialog open={modalOpen} onOpenChange={onClose}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Confirm deletion</DialogTitle>
                    <DialogDescription>
                        This cannot be undone!
                    </DialogDescription>
                </DialogHeader>
                <DialogFooter>
                    <DialogClose asChild>
                        <Button variant="outline" >Cancel</Button>
                    </DialogClose>
                    <DialogClose asChild>
                        <Button variant="destructive" type="submit" onClick={() => onConfirm(objectId)}>Delete</Button>
                    </DialogClose>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}
